import { InputProps } from "@/app/types/types";

export const generateData = (translations: Record<string, any>, lang: string) => {
    return [
        {
            name: "email",
            label: translations[lang]["Email"],
            type: "email",
            required: true,
            placeholder: translations[lang]["Email"],
        },
        {
            name: "password",
            label: translations[lang]["Password"],
            type: "password",
            required: true,
            min: 6,
            placeholder: translations[lang]["Password"],
        },
        {
            name: "name",
            label: translations[lang]["Name"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Name"],
        },
        {
            name: "type",
            label: translations[lang]["Type"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Type"],
        },
        {
            name: "profession",
            label: translations[lang]["Profession"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Profession"],
        },
        {
            name: "description",
            label: translations[lang]["Description"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Description"],
        },
        {
            name: "companies",
            label: translations[lang]["Companies"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Companies"],
        },
        {
            name: "representative_name",
            label: translations[lang]["Representative Name"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Representative Name"],
        },
        {
            name: "representative_role",
            label: translations[lang]["Representative Role"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Representative Role"],
        },
        {
            name: "website",
            label: translations[lang]["Website"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Website"],
        },
        {
            name: "phone",
            label: translations[lang]["Phone"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Phone"],
        },
        {
            name: "facebook",
            label: translations[lang]["Facebook"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Facebook"],
        },
        {
            name: "linkedin",
            label: translations[lang]["LinkedIn"],
            type: "text",
            required: false,
            placeholder: translations[lang]["LinkedIn"],
        },
        {
            name: "instagram",
            label: translations[lang]["Instagram"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Instagram"],
        },
        {
            name: "behance",
            label: translations[lang]["Behance"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Behance"],
        },
        {
            name: "viber",
            label: translations[lang]["Viber"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Viber"],
        },
        {
            name: "telegram",
            label: translations[lang]["Telegram"],
            type: "text",
            required: false,
            placeholder: translations[lang]["Telegram"],
        },
        {
            name: "whatsapp",
            label: translations[lang]["WhatsApp"],
            type: "text",
            required: false,
            placeholder: translations[lang]["WhatsApp"],
        },
        // {
        //     name: "color",
        //     label: translations[lang]["Color"],
        //     type: "text",
        //     required: false,
        //     placeholder: translations[lang]["Color"],
        // },
        // {
        //     name: "font",
        //     label: translations[lang]["Font"],
        //     type: "text",
        //     required: false,
        //     placeholder: translations[lang]["Font"],
        // },
    ] as InputProps[];
};
